# Generated by Django 4.1.4 on 2022-12-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="nivel",
            field=models.CharField(
                choices=[("A", "Avançado"), ("B", "Básico"), ("I", "Intermediário")],
                default="B",
                max_length=1,
            ),
        ),
    ]
